### PR TITLE
now compatible with allenlp==2.4.0

### PR DESCRIPTION
**Pull request by Snoussi88**
some minor tweaks

### CODE REVIEW

**Comment by thiborose** [comment]
Thanks for contributing! 

I tried to re-install gecko from scratch ; Indeed Allennlp now poses a problem.  But it seems that your patch doesn't solve it on my machine. Does everything work out for you?

**Comment by thiborose** [comment]
I actually got gecko running with the default settings. Everything works fine to me. I guess this PR is related to  #23

**Comment by Snoussi88** [comment]
> Thanks for contributing!
> 
> I tried to re-install gecko from scratch ; Indeed Allennlp now poses a problem. But it seems that your patch doesn't solve it on my machine. Does everything work out for you?

no, not yet at least but i thought if i made it work with the recent depencies it might work ? and what are the default settings are you referring to ?

**Comment by thiborose** [comment]
Closing as does no longer apply

**Pull request closed without merging**
